### ISSUE TITLE
Wasm based Compose for Web support

### ISSUE THREAD

**Issue by joreilly** [overpas/compose-treemap-chart#98]
Hi, is there any plans to create a version that works with Wasm based Compose for Web?

**Comment by overpas** [comment]
Maybe, but I don't have exact ETA

**Comment by joreilly** [comment]
@overpas I tried making changes but having some issues publishing locally to test (more details in https://github.com/overpas/compose-treemap-chart/pull/99).

**Comment by joreilly** [comment]
@overpas I opened PR to add wasm support....seems to work fine

<img width="1588" alt="Screenshot 2024-02-25 at 17 02 31" src="https://github.com/overpas/compose-treemap-chart/assets/6302/3447644e-c38c-49a1-91ca-954d6ab12e3e">

**Comment by overpas** [comment]
Having some troubles with 0.1.1 publication, I'll probably create and delete the new release multiple times. I'll close the issue when it's resolved

**Comment by overpas** [comment]
0.1.1 artifacts with wasm support should be available on Maven Central now

**Comment by joreilly** [comment]
Pulling in 0.1.1 and treemap dependencies not resolving for some reason....not sure if issue in my changes...

<img width="621" alt="Screenshot 2024-02-26 at 19 54 45" src="https://github.com/overpas/compose-treemap-chart/assets/6302/21133b51-9926-45ea-9300-fcb8768a081b">

**Comment by joreilly** [comment]
nvm, caching issue on my side....working now.

**Comment by overpas** [comment]
Seems to be there 
https://repo1.maven.org/maven2/io/github/overpas/treemap-chart-wasm-js/0.1.1/
https://repo1.maven.org/maven2/io/github/overpas/treemap-chart-compose-wasm-js/0.1.1/

**Comment by LouisCAD** [comment]
Publishing on Maven Central usually takes about 15 minutes to be visible because of how their CDN is set up. Maybe it was that?
